### ISSUE TITLE
links in plot seem wrong

### ISSUE THREAD

**Issue by mirestrepo** [rened/QuickShiftClustering.jl#2]
Hi,

When I tried the given example I get this plot. Seems like links are wrong?
![screen shot 2017-05-10 at 3 27 24 pm](https://cloud.githubusercontent.com/assets/1238840/25917244/66558cc2-3595-11e7-95d7-ad05aa9c86cd.png)

I'm using master

```
using QuickShiftClustering
using PyPlot
using FunctionalData
G = @p map unstack(1:10) (x->10*randn(2,1).+randn(2,100)) | flatten

Z = quickshift(G)
labels = quickshiftlabels(Z)
quickshiftplot(Z,G, labels)
```

**Comment by rened** [comment]
Thanks for reporting this! Seems the behaviour of `NearestNeighbors.inrange` changed and was no longer sorting by actual distance but only sorting the point IDs.

Fixed via 65823c26182e096a735ecd3

Please try whether it works for your with the current master (`Pkg.checkout("QuickShiftClustering")`).
